/*
 * This source file was generated by the Gradle 'init' task
 */
package wash24x;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Test;
import org.testfx.framework.junit5.ApplicationTest;
import javafx.stage.Stage;
import javafx.scene.control.Button;
import javafx.scene.control.Label;

public class AppTest extends ApplicationTest {

    @Override
    public void start(Stage stage) {
        new App().start(stage);
    }

    @Test
    void testUILabelsExist() {
        assertNotNull(lookup("🐦‍🔥 Wash24x").queryLabeled());
        assertNotNull(lookup("🧺Laundry service that you can trust").queryLabeled());
    }

    @Test
    void testButtonsExist() {
        assertNotNull(lookup("LoginApp").queryButton());
        assertNotNull(lookup("Register").queryButton());
    }

    @Test
    void testClickLoginButton() {
        clickOn("LoginApp");
        assertFalse(lookup("🐦‍🔥 Wash24x").queryLabeled().isVisible()); // ตรวจสอบว่าเปลี่ยน Scene แล้ว
    }

    @Test
    void testClickRegisterButton() {
        clickOn("Register");
        assertFalse(lookup("🐦‍🔥 Wash24x").queryLabeled().isVisible()); // ตรวจสอบว่าเปลี่ยน Scene แล้ว
    }

    @Test
    void testShowMainMenu() {
        App.showMainMenu();
        assertTrue(lookup("🐦‍🔥 Wash24x").queryLabeled().isVisible());
    }
}
