/*
 * This source file was generated by the Gradle 'init' task
 */
package wash24x;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Test;
import org.testfx.framework.junit5.ApplicationTest;
import javafx.stage.Stage;
import javafx.scene.control.*;
import javafx.scene.layout.VBox;

public class LoginTest extends ApplicationTest {

    private Stage primaryStage;

    @Override
    public void start(Stage stage) {
        primaryStage = stage;
        new Login(primaryStage);
    }

    @Test
    void testUIElementsExist() {
        assertNotNull(lookup("📋 Login to Wash24x 🐦‍🔥").query());
        assertNotNull(lookup(".text-field").query()); // Username field
        assertNotNull(lookup(".password-field").query()); // Password field
        assertNotNull(lookup("Login").queryButton());
        assertNotNull(lookup("Back").queryButton());
    }

    @Test
    void testLoginSuccess() {
        clickOn(".text-field").write("testuser");
        clickOn(".password-field").write("correctpassword");
        clickOn("Login");

        // ตรวจสอบว่ามีข้อความแจ้งว่าเข้าสู่ระบบสำเร็จ
        Label messageLabel = lookup(".label").queryAs(Label.class);
        assertEquals("Login Successful! Role: staff", messageLabel.getText());
    }

    @Test
    void testLoginFailure() {
        clickOn(".text-field").write("testuser");
        clickOn(".password-field").write("wrongpassword");
        clickOn("Login");

        // ตรวจสอบว่ามีข้อความแจ้งเตือนแสดงขึ้น
        Label messageLabel = lookup(".label").queryAs(Label.class);
        assertEquals("Invalid Username or Password", messageLabel.getText());
    }

    @Test
    void testBackButton() {
        clickOn("Back");
        assertTrue(primaryStage.getScene().getRoot() instanceof VBox); // ตรวจสอบว่าเปลี่ยนกลับไปที่ Main Menu
    }
}

