/*
 * This source file was generated by the Gradle 'init' task
 */
package wash24x;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Test;
import org.testfx.framework.junit5.ApplicationTest;
import javafx.stage.Stage;
import javafx.scene.control.*;
import javafx.scene.layout.VBox;

public class TopUptest extends ApplicationTest {

    private Stage primaryStage;

    @Override
    public void start(Stage stage) {
        primaryStage = stage;
        new TopUp(primaryStage);
    }

    @Test
    void testUIElementsExist() {
        assertNotNull(lookup("💲 Top-Up System").query());
        assertNotNull(lookup("Amount: ").queryLabeled());
        assertNotNull(lookup("Bank: ").queryLabeled());
        assertNotNull(lookup("Enter PIN: ").queryLabeled());
        assertNotNull(lookup(".text-field").query()); // Amount Field
        assertNotNull(lookup(".password-field").query()); // PIN Field
        assertNotNull(lookup("✔ Confirm Top-Up").queryButton());
        assertNotNull(lookup("↩ Back").queryButton());
    }

    @Test
    void testValidTopUp() {
        clickOn(".text-field").write("500");
        clickOn(".password-field").write("1234");
        clickOn("✔ Confirm Top-Up");

        Label successLabel = lookup(".label").queryAs(Label.class);
        assertTrue(successLabel.getText().contains("Top-Up Successful!"));
    }

    @Test
    void testInvalidAmountZero() {
        clickOn(".text-field").write("0");
        clickOn(".password-field").write("1234");
        clickOn("✔ Confirm Top-Up");

        assertTrue(lookup("Invalid Amount").queryLabeled().isVisible());
    }

    @Test
    void testExceedMaxAmount() {
        clickOn(".text-field").write("1500");
        clickOn(".password-field").write("1234");
        clickOn("✔ Confirm Top-Up");

        assertTrue(lookup("Limit Exceeded").queryLabeled().isVisible());
    }

    @Test
    void testMissingPIN() {
        clickOn(".text-field").write("500");
        clickOn("✔ Confirm Top-Up");

        assertTrue(lookup("PIN Required").queryLabeled().isVisible());
    }

    @Test
    void testInvalidAmountInput() {
        clickOn(".text-field").write("ABC");
        clickOn(".password-field").write("1234");
        clickOn("✔ Confirm Top-Up");

        assertTrue(lookup("Invalid Input").queryLabeled().isVisible());
    }

    @Test
    void testBackButton() {
        clickOn("↩ Back");
        assertTrue(primaryStage.getScene().getRoot() instanceof VBox); // ตรวจสอบว่ากลับไปหน้าเมนูหลัก
    }
}
